//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vscommerce.Category {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/dbManager.vscommerceDB")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
    [System.SerializableAttribute()]
    public partial class ManagerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Category.ICategoryManager")]
    public interface ICategoryManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/getCategories", ReplyAction="http://tempuri.org/ICategoryManager/getCategoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.Category.ManagerFault), Action="http://tempuri.org/ICategoryManager/getCategoriesManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        vscommerce.Category.Category[] getCategories(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/getCategories", ReplyAction="http://tempuri.org/ICategoryManager/getCategoriesResponse")]
        System.Threading.Tasks.Task<vscommerce.Category.Category[]> getCategoriesAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/getCategoryById", ReplyAction="http://tempuri.org/ICategoryManager/getCategoryByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.Category.ManagerFault), Action="http://tempuri.org/ICategoryManager/getCategoryByIdManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        vscommerce.Category.Category getCategoryById(string email, string password, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/getCategoryById", ReplyAction="http://tempuri.org/ICategoryManager/getCategoryByIdResponse")]
        System.Threading.Tasks.Task<vscommerce.Category.Category> getCategoryByIdAsync(string email, string password, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/updateCategory", ReplyAction="http://tempuri.org/ICategoryManager/updateCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.Category.ManagerFault), Action="http://tempuri.org/ICategoryManager/updateCategoryManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool updateCategory(string email, string password, vscommerce.Category.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/updateCategory", ReplyAction="http://tempuri.org/ICategoryManager/updateCategoryResponse")]
        System.Threading.Tasks.Task<bool> updateCategoryAsync(string email, string password, vscommerce.Category.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/createCategory", ReplyAction="http://tempuri.org/ICategoryManager/createCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.Category.ManagerFault), Action="http://tempuri.org/ICategoryManager/createCategoryManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool createCategory(string email, string password, vscommerce.Category.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/createCategory", ReplyAction="http://tempuri.org/ICategoryManager/createCategoryResponse")]
        System.Threading.Tasks.Task<bool> createCategoryAsync(string email, string password, vscommerce.Category.Category category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryManagerChannel : vscommerce.Category.ICategoryManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryManagerClient : System.ServiceModel.ClientBase<vscommerce.Category.ICategoryManager>, vscommerce.Category.ICategoryManager {
        
        public CategoryManagerClient() {
        }
        
        public CategoryManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public vscommerce.Category.Category[] getCategories(string email, string password) {
            return base.Channel.getCategories(email, password);
        }
        
        public System.Threading.Tasks.Task<vscommerce.Category.Category[]> getCategoriesAsync(string email, string password) {
            return base.Channel.getCategoriesAsync(email, password);
        }
        
        public vscommerce.Category.Category getCategoryById(string email, string password, int ID) {
            return base.Channel.getCategoryById(email, password, ID);
        }
        
        public System.Threading.Tasks.Task<vscommerce.Category.Category> getCategoryByIdAsync(string email, string password, int ID) {
            return base.Channel.getCategoryByIdAsync(email, password, ID);
        }
        
        public bool updateCategory(string email, string password, vscommerce.Category.Category category) {
            return base.Channel.updateCategory(email, password, category);
        }
        
        public System.Threading.Tasks.Task<bool> updateCategoryAsync(string email, string password, vscommerce.Category.Category category) {
            return base.Channel.updateCategoryAsync(email, password, category);
        }
        
        public bool createCategory(string email, string password, vscommerce.Category.Category category) {
            return base.Channel.createCategory(email, password, category);
        }
        
        public System.Threading.Tasks.Task<bool> createCategoryAsync(string email, string password, vscommerce.Category.Category category) {
            return base.Channel.createCategoryAsync(email, password, category);
        }
    }
}
