//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vscommerce.User {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
    [System.SerializableAttribute()]
    public partial class ManagerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/dbManager.vscommerceDB")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fiscalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((this.birthdayField.Equals(value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fiscalCode {
            get {
                return this.fiscalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.fiscalCodeField, value) != true)) {
                    this.fiscalCodeField = value;
                    this.RaisePropertyChanged("fiscalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="User.IUserManager")]
    public interface IUserManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/Login", ReplyAction="http://tempuri.org/IUserManager/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/LoginManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/Login", ReplyAction="http://tempuri.org/IUserManager/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUserByEmail", ReplyAction="http://tempuri.org/IUserManager/getUserByEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/getUserByEmailManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        vscommerce.User.User getUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUserByEmail", ReplyAction="http://tempuri.org/IUserManager/getUserByEmailResponse")]
        System.Threading.Tasks.Task<vscommerce.User.User> getUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/existUser", ReplyAction="http://tempuri.org/IUserManager/existUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/existUserManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool existUser(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/existUser", ReplyAction="http://tempuri.org/IUserManager/existUserResponse")]
        System.Threading.Tasks.Task<bool> existUserAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUserById", ReplyAction="http://tempuri.org/IUserManager/getUserByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/getUserByIdManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        vscommerce.User.User getUserById(string email, string password, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUserById", ReplyAction="http://tempuri.org/IUserManager/getUserByIdResponse")]
        System.Threading.Tasks.Task<vscommerce.User.User> getUserByIdAsync(string email, string password, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUsers", ReplyAction="http://tempuri.org/IUserManager/getUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/getUsersManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        vscommerce.User.User[] getUsers(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/getUsers", ReplyAction="http://tempuri.org/IUserManager/getUsersResponse")]
        System.Threading.Tasks.Task<vscommerce.User.User[]> getUsersAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/updateUser", ReplyAction="http://tempuri.org/IUserManager/updateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/updateUserManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool updateUser(vscommerce.User.User userUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/updateUser", ReplyAction="http://tempuri.org/IUserManager/updateUserResponse")]
        System.Threading.Tasks.Task<bool> updateUserAsync(vscommerce.User.User userUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/createUser", ReplyAction="http://tempuri.org/IUserManager/createUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(vscommerce.User.ManagerFault), Action="http://tempuri.org/IUserManager/createUserManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Manager")]
        bool createUser(vscommerce.User.User userUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/createUser", ReplyAction="http://tempuri.org/IUserManager/createUserResponse")]
        System.Threading.Tasks.Task<bool> createUserAsync(vscommerce.User.User userUpdate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerChannel : vscommerce.User.IUserManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerClient : System.ServiceModel.ClientBase<vscommerce.User.IUserManager>, vscommerce.User.IUserManager {
        
        public UserManagerClient() {
        }
        
        public UserManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public vscommerce.User.User getUserByEmail(string email) {
            return base.Channel.getUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<vscommerce.User.User> getUserByEmailAsync(string email) {
            return base.Channel.getUserByEmailAsync(email);
        }
        
        public bool existUser(string email) {
            return base.Channel.existUser(email);
        }
        
        public System.Threading.Tasks.Task<bool> existUserAsync(string email) {
            return base.Channel.existUserAsync(email);
        }
        
        public vscommerce.User.User getUserById(string email, string password, int ID) {
            return base.Channel.getUserById(email, password, ID);
        }
        
        public System.Threading.Tasks.Task<vscommerce.User.User> getUserByIdAsync(string email, string password, int ID) {
            return base.Channel.getUserByIdAsync(email, password, ID);
        }
        
        public vscommerce.User.User[] getUsers(string email, string password) {
            return base.Channel.getUsers(email, password);
        }
        
        public System.Threading.Tasks.Task<vscommerce.User.User[]> getUsersAsync(string email, string password) {
            return base.Channel.getUsersAsync(email, password);
        }
        
        public bool updateUser(vscommerce.User.User userUpdate) {
            return base.Channel.updateUser(userUpdate);
        }
        
        public System.Threading.Tasks.Task<bool> updateUserAsync(vscommerce.User.User userUpdate) {
            return base.Channel.updateUserAsync(userUpdate);
        }
        
        public bool createUser(vscommerce.User.User userUpdate) {
            return base.Channel.createUser(userUpdate);
        }
        
        public System.Threading.Tasks.Task<bool> createUserAsync(vscommerce.User.User userUpdate) {
            return base.Channel.createUserAsync(userUpdate);
        }
    }
}
